import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
//condensed
const inter = Open_Sans({ weight : "300", style : "normal", subsets : ["hebrew"]});

export const metadata: Metadata = {
  title: "Bouhady",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
